# Generated by Django 5.0.2 on 2024-09-06 17:36

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_adminprofile_profile_picture_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artistprofile",
            name="samples",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(),
                upload_to="file/",
            ),
        ),
    ]
