# Generated by Django 5.0.2 on 2024-09-06 17:49

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_alter_adminprofile_profile_picture_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminprofile",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to="image/"),
        ),
        migrations.AlterField(
            model_name="artistprofile",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to="image/"),
        ),
        migrations.AlterField(
            model_name="artistprofile",
            name="samples",
            field=models.ImageField(
                blank=True,
                storage=cloudinary_storage.storage.RawMediaCloudinaryStorage,
                upload_to="file/",
            ),
        ),
        migrations.AlterField(
            model_name="customerprofile",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to="image/"),
        ),
        migrations.AlterField(
            model_name="historicaladminprofile",
            name="profile_picture",
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="historicalartistprofile",
            name="profile_picture",
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="historicalcustomerprofile",
            name="profile_picture",
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
