# Generated by Django 5.0.2 on 2024-09-08 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_alter_adminprofile_profile_picture_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artistprofile",
            name="samples",
            field=models.FileField(blank=True, null=True, upload_to="file/"),
        ),
        migrations.AlterField(
            model_name="historicalartistprofile",
            name="samples",
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
